import React from 'react';

const Blog = () => {
    return (
        <div>
            <div> <div className="p-5" >  <h1  className="text-3xl">How will you improve the performance of a react application?</h1> <br/>  <p> There are some steps for improving the performance of react application such as</p> <li>Using immutable data structure helps improving performance </li> <li> Optimizing Dependency</li>  <li>	Use react fragments to avoid additional html element wrappers</li>  <li>	Use CSS animation instead of JS animation.</li> <li>Use production build</li> <li>use react memo for component memoization</li>  <li>Keeping component state local where necessary</li> </div> <div className="p-5"  > <h1  className="text-3xl">What are the different ways to manage a state in a React Application?</h1> <br/>  <p>There are four main types of state you need to properly manage in your react apps. </p> <li>Local State.</li> <li>Global State </li>  <li>Server State	</li> <li>Url State</li> <p>Local state can be easily manageable .Context API can be used for managed state.Context API is way to avoid props drilling.To manage global state,tested third party libraries like 
                Zustand is useful.Server state is challenging to manage.Everyone just need to fetch data and display it in the page.URL state is easily managable if are using framework like next js or current version of React Hooks</p>  </div>      <div className="p-5" >  <h1  className="text-3xl">How Does Prototypical inheritance work?</h1> <br/>   <li>Prototypical inheritance is a feature in javascript used to add methods and properties in objects</li> <li>Prototype method is used to inherit properties and methods of another object. </li>  <li>It allows us to reuse the properties or methods from one Javascript object to another through a reference pointer function.	</li>   <li>All javascript objects inherit properties and methods from a prototype.	</li>    </div> <div className="p-5" >  <h1 className="text-3xl mt-5 "  > You have an array of products. Each product has a name, price, description, etc. How will you implement a search to find products by name?</h1>  <p className="text-xl p-5"> We can use array.find(productname) method to find the exact product.By using this method,we can easily find the product name.  </p>  </div>   <div className="p-5" > <h1 className="text-3xl mt-5 "  > What is a unit test? Why should write unit tests?</h1> <p className="p-5"> The main objective of unit testing is to  written code to test and determine if it works.
Unit testing is an important  in the development process, because if done correctly, it can help detect early errors in code.Developers write unit tests for their code to make sure that the code works correctly. This helps to detect and protect against bugs in the future.
Sometimes developers write unit tests first, then write the code. This approach is also known as test-driven development.  </p>   </div>  </div>
        </div>
    );
};

export default Blog;